fullnameOverride: o1ves

grafana:
  fullnameOverride: o1ves-grafana
  enabled: true
  defaultDashboardsTimezone: Asia/Taipei
  adminPassword: smo
  service:
    type: NodePort
    nodePort: 30000
  persistence:
    enabled: true
    storageClassName: "local-storage-grafana"
    size: 10Gi

influxdb2:
  fullnameOverride: o1ves-influxdb2
  enabled: true
  persistence:
    enabled: true
    storageClass: "local-storage-influxdb2"
    accessMode: ReadWriteOnce
    size: 50Gi
    mountPath: /var/lib/influxdb2
    subPath: ""
  image:
    repository: influxdb
    tag: 2.3.0-alpine
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 80
    targetPort: 8086
    nodePort: 30001
    annotations: {}
    labels: {}
    portName: http

dmaap-influxdb-adapter:
  enabled: true
  image:
    repository: hsukevin121/dmaap-influxdb-adapter
  influxdb:
    host: o1ves-influxdb2
    port: 80
    tokenSecret: o1ves-influxdb2-auth
    org: influxdata
  logLevel: DEBUG

  rules:
    - topic: unauthenticated.SEC_FAULT_OUTPUT
      rules:
        - bucket: o1_fault_event
          measurement: BBU_FM_Event
          matches:
            - key: event.commonEventHeader.domain
              value: fault
          tags:
            - key: eventType
              field: event.commonEventHeader.eventType
          fields:
            - key: eventName
              field: event.commonEventHeader.eventName
              type: string
            - key: sourceName
              field: event.commonEventHeader.sourceName
              type: string
            - key: SystemDN
              field: event.commonEventHeader.nfVendorName
              type: string
            - key: EventSeverity
              field: event.faultFields.eventSeverity
              type: string
            - key: ProbableCause
              field: event.faultFields.specificProblem
              type: string
            - key: AlarmId
              field: event.faultFields.alarmCondition
              type: string
            - key: IsCleared
              field: event.faultFields.vfStatus
              type: string


    - topic: unauthenticated.SEC_OTHER_OUTPUT
      rules:
        - bucket: PDCP_Throughput
          measurement: ue_sum_info
          matches:
            - key: event.commonEventHeader.domain
              value: other
            - key: event.otherFields.arrayOfNamedHashMap[0].name
              value: total
          tags:
            - key: name
              field: event.otherFields.arrayOfNamedHashMap[0].name
          fields:
            - key: num_of_ue
              field: event.otherFields.arrayOfNamedHashMap[0].hashMap.num_of_ue
              type: int
            - key: total_ul_tp
              field: event.otherFields.arrayOfNamedHashMap[0].hashMap.total_ul_tp
              type: float
            - key: total_ul_pkt
              field: event.otherFields.arrayOfNamedHashMap[0].hashMap.total_ul_pkt
              type: int
            - key: total_dl_tp
              field: event.otherFields.arrayOfNamedHashMap[0].hashMap.total_dl_tp
              type: float
            - key: total_dl_pkt
              field: event.otherFields.arrayOfNamedHashMap[0].hashMap.total_dl_pkt
              type: int
        - bucket: PDCP_Throughput
          measurement: ue_info
          matches:
            - key: event.commonEventHeader.domain
              value: other
            - key: event.otherFields.arrayOfNamedHashMap[0].name
              value: personal
          tags:
            - key: name
              field: event.otherFields.arrayOfNamedHashMap[0].name
          fields:
            - key: ue_id
              field: event.otherFields.arrayOfNamedHashMap[0].hashMap.ue_id
              type: int
            - key: ul_tp
              field: event.otherFields.arrayOfNamedHashMap[0].hashMap.ul_tp
              type: float
            - key: ul_pkt
              field: event.otherFields.arrayOfNamedHashMap[0].hashMap.ul_pkt
              type: int
            - key: dl_tp
              field: event.otherFields.arrayOfNamedHashMap[0].hashMap.dl_tp
              type: float
            - key: dl_pkt
              field: event.otherFields.arrayOfNamedHashMap[0].hashMap.dl_pkt
              type: int
        - bucket: BBU_Info
          measurement: BBU_Info
          matches:
            - key: event.commonEventHeader.domain
              value: other
            - key: event.otherFields.arrayOfNamedHashMap[0].name
              value: ran1
          tags:
            - key: name
              field: event.otherFields.arrayOfNamedHashMap[0].name
          fields:
            - key: PLMNID
              field: event.otherFields.arrayOfNamedHashMap[0].hashMap.PLMNID
              type: string
            - key: BBU_IP
              field: event.otherFields.arrayOfNamedHashMap[0].hashMap.BBU_IP
              type: string
            - key: BBU_NETMASK
              field: event.otherFields.arrayOfNamedHashMap[0].hashMap.BBU_NETMASK
              type: string
            - key: BBU_Gateway_IP
              field: event.otherFields.arrayOfNamedHashMap[0].hashMap.BBU_Gateway_IP
              type: string
            - key: AMF_IP
              field: event.otherFields.arrayOfNamedHashMap[0].hashMap.AMF_IP
              type: string
            - key: gNB_ID
              field: event.otherFields.arrayOfNamedHashMap[0].hashMap.gNB_ID
              type: string
        - bucket: BBU_Info
          measurement: BBU_Info
          matches:
            - key: event.commonEventHeader.domain
              value: other
            - key: event.otherFields.arrayOfNamedHashMap[0].name
              value: ran2
          tags:
            - key: name
              field: event.otherFields.arrayOfNamedHashMap[0].name
          fields:
            - key: PLMNID
              field: event.otherFields.arrayOfNamedHashMap[0].hashMap.PLMNID
              type: string
            - key: BBU_IP
              field: event.otherFields.arrayOfNamedHashMap[0].hashMap.BBU_IP
              type: string
            - key: BBU_NETMASK
              field: event.otherFields.arrayOfNamedHashMap[0].hashMap.BBU_NETMASK
              type: string
            - key: BBU_Gateway_IP
              field: event.otherFields.arrayOfNamedHashMap[0].hashMap.BBU_Gateway_IP
              type: string
            - key: AMF_IP
              field: event.otherFields.arrayOfNamedHashMap[0].hashMap.AMF_IP
              type: string
            - key: gNB_ID
              field: event.otherFields.arrayOfNamedHashMap[0].hashMap.gNB_ID
              type: string


buckets:
  - name: o1_performance
  - name: o1_fault_event
  - name: PDCP_Throughput
  - name: BBU_Info
  - name: socket_info


image:
  pullPolicy: IfNotPresent
