apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dmaap-influxdb-adapter.fullname" . }}-rules
  labels:
    {{- include "dmaap-influxdb-adapter.labels" . | nindent 4 }}
data:
  rules.yml: |-
    {{- toYaml .Values.rules | nindent 4 }}
---